import Head from 'next/head'
import * as React from 'react'
import { NavBar } from 'src/components/NavBar/index'
import { Footer } from 'src/components/Footer/index';
import { CallToAction } from 'pages/landingPage/CallToAction';



export default function Home() {
  return (
    <>
      <Head>
        <title>2BNK</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar/>
      <CallToAction/>
      <Footer/>
    </>
  )
}
